[functions]
  node_bundler = "esbuild"
  external_node_modules = []
  [functions.timeout]
    function_duration = 30

[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"